inherit_from: .rubocop_todo.yml

AllCops:
  RunRailsCops: true
  Exclude:
    - 'db/schema.rb'

Style/RegexpLiteral:
  Exclude:
    - 'Guardfile'

Lint/HandleExceptions:
  Exclude:
    - 'bin/*'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20
