# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58f9e0fdb155f943ac03ab0293d3f29b44163d9d37e99145c2f6f6c6a205f6c92cf225fa48b74b211fddc610e59ac814544d2d256b758baf4da2260f53d34f41

test:
  secret_key_base: bab725d9b5ead7c4d6e21249e39db27113ea3e43f63e038925c41391b728674c94134c7d50462db5de43f240f39568ade5469f5bd9b6b986523976c5132f1c94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
